# Generated by Django 5.2 on 2025-04-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'verbose_name': 'venda'},
        ),
    ]
