# Generated by Django 5.2 on 2025-04-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_vendas_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente'},
        ),
    ]
